### ISSUE TITLE
All routes throwing 404 (Neos 5.1.5)

### ISSUE THREAD

**Issue by timvonwerne** [breadlesscode/neos-nodetypes-folder#10]
All routes are throwing a 404 error on Neos 5.1.5.
Even the ones that are not in a folder.

**Comment by Sebobo** [comment]
Thanks, can reproduce it with Neos 5. We have to fix this and then mark compatible with Neos 5.

**Comment by Sebobo** [comment]
I now spent some time on this and it seems to somehow relate to the handler not being able anymore to detect the language dimensions from the uri segments. Url with language segments seem to work.
But I haven't found out why yet. Will continue my research.
