### ISSUE TITLE
Unexpected 'bool' in FrontendNodeRoutePartHandler:28

### ISSUE THREAD

**Issue by timvonwerne** [breadlesscode/neos-nodetypes-folder#13]
The following error occurs with the current clone of master branch on Neos 5.1.6:

```
syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

  Type: ParseError
  File: Packages/Plugins/Breadlesscode.NodeTypes.Folder/Classes/Package/FrontendNod
        eRoutePartHandler.php
  Line: 28
```

**Comment by Benjamin-K** [comment]
This package requires php 7.4 feature "Typed properties in classes.". It seems like you are using a lower version than php 7.4.

**Comment by breadlesscode** [comment]
You can make a PR and remove the type hint from the property. That should be no problem :) 

https://github.com/breadlesscode/neos-nodetypes-folder/blob/master/Classes/Package/FrontendNodeRoutePartHandler.php#L28

PS: Thanks @Benjamin-K for answering this issue  😀
