### ISSUE TITLE
HideUriSegment not showing in Neos 4.1

### ISSUE THREAD

**Issue by shuffgy** [breadlesscode/neos-nodetypes-folder#5]
I'm not quite sure whats wrong, but i have this package in Neos 3.3.8 and its working fine,

In my new installation (4.1) i dont have the checkbox for `HideUriSegment`.

Could you please check that out?

**Comment by breadlesscode** [comment]
Thanks for reporting, I will take a look asop.

**Comment by Benjamin-K** [comment]
This is because the used inspector group "redirect" is not/no longer available in Neos 4.1. If you use Neos > 3.x, Version 1.0.0 of this package will be used, because it had no strict version on the required packages, only `"neos/flow": "*"`.
